service: import-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: Aliaksandr_Baryskin
  environment:
    AWS_GENERAL_REGION: 'us-east-1'
  iamRoleStatements:
    - Effect: 'Allow'
      Action: ['s3:*']
      Resource: 
        - 'arn:aws:s3:::vue-shop-import-bucket/*'
    - Effect: 'Allow'
      Action: ['sqs:SendMessage']
      Resource: 
        - 'arn:aws:sqs:us-east-1:222048563468:catalogItemsQueue'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  importProductsFile:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true
  importFileParser:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: vue-shop-import-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
